[Project Meta]
name="SchoolProjects"
version="1.5"
description="Programme und Projekte die im Rahmen des Informatikunterrichts entstanden sind"

[Structure]
project.toml="/project.toml"
readme="/readme.md"
pip_req="/requirements.txt"
gitignore="/.gitignore"
src_dir="/src"

[Venv]
win_venv="/.venv"
gnu_venv="/venv"

[Scripts]
main_script="/src/main.py"
turle_project_script="/src/Themen/Turtle/main.py"
turle_project_init_script="/src/Themen/Turtle/__init__.py"
testing_script="/src/Vorschau.py"

[LICENSE]
path="/LICENSE"
type="MIT License"